### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by medyagh** [pressly/chi#156]
I get this panic, i see there was an old closed issue, could it same issue ?

I am using the v2.0.0 .

```
panic: runtime error: invalid memory address or nil pointer dereference
2017/02/14 01:30:25 goroutine 61 [running]:
runtime/debug.Stack(0xc4200da5a0, 0x1c5b4c0, 0xc4205b61a0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
smasher/vendor/github.com/pressly/chi/middleware.Recoverer.func1.1(0xc4200da5a0, 0x7f02b98f81e0, 0xc4204a22c0)
	/go/src/smasher/vendor/github.com/pressly/chi/middleware/recoverer.go:23 +0x82
panic(0x133a100, 0xc42000a040)
	/usr/local/go/src/runtime/panic.go:458 +0x243
main.start_http_server.func4(0x7f02b98f81e0, 0xc4204a22c0, 0xc4200da960)
	/go/src/smasher/main.go:150 +0x283
net/http.HandlerFunc.ServeHTTP(0xc420462310, 0x7f02b98f81e0, 0xc4204a22c0, 0xc4200da960)
	/usr/local/go/src/net/http/server.go:1726 +0x44
smasher/vendor/github.com/pressly/chi.(*Mux).routeHTTP(0xc4202f10e0, 0x7f02b98f81e0, 0xc4204a22c0, 0xc4200da960)
	/go/src/smasher/vendor/github.com/pressly/chi/mux.go:386 +0x216
smasher/vendor/github.com/pressly/chi.(*Mux).(smasher/vendor/github.com/pressly/chi.routeHTTP)-fm(0x7f02b98f81e0, 0xc4204a22c0, 0xc4200da960)
	/go/src/smasher/vendor/github.com/pressly/chi/mux.go:325 +0x48
net/http.HandlerFunc.ServeHTTP(0xc4204622b0, 0x7f02b98f81e0, 0xc4204a22c0, 0xc4200da960)
	/usr/local/go/src/net/http/server.go:1726 +0x44
smasher/vendor/github.com/pressly/chi/middleware.Timeout.func1.1(0x7f02b98f81e0, 0xc4204a22c0, 0xc4200da960)
	/go/src/smasher/vendor/github.com/pressly/chi/middleware/timeout.go:44 +0x117
net/http.HandlerFunc.ServeHTTP(0xc4205598c0, 0x7f02b98f81e0, 0xc4204a22c0, 0xc4200da690)
	/usr/local/go/src/net/http/server.go:1726 +0x44
smasher/vendor/github.com/pressly/chi/middleware.CloseNotify.func1(0x7f02b98f81e0, 0xc4204a22c0, 0xc4200da690)
	/go/src/smasher/vendor/github.com/pressly/chi/middleware/closenotify17.go:39 +0x1bb
net/http.HandlerFunc.ServeHTTP(0xc4205598e0, 0x7f02b98f81e0, 0xc4204a22c0, 0xc4200da5a0)
	/usr/local/go/src/net/http/server.go:1726 +0x44
smasher/vendor/github.com/pressly/chi/middleware.Recoverer.func1(0x7f02b98f81e0, 0xc4204a22c0, 0xc4200da5a0)
	/go/src/smasher/vendor/github.com/pressly/chi/middleware/recoverer.go:32 +0x9f
net/http.HandlerFunc.ServeHTTP(0xc420559900, 0x7f02b98f81e0, 0xc4204a22c0, 0xc4200da5a0)
	/usr/local/go/src/net/http/server.go:1726 +0x44
smasher/vendor/github.com/pressly/chi/middleware.RequestLogger.func1.1(0x1c5e080, 0xc4204cd1e0, 0xc4200da4b0)
	/go/src/smasher/vendor/github.com/pressly/chi/middleware/logger.go:40 +0x1b4
net/http.HandlerFunc.ServeHTTP(0xc420425890, 0x1c5e080, 0xc4204cd1e0, 0xc4200da4b0)
	/usr/local/go/src/net/http/server.go:1726 +0x44
smasher/vendor/github.com/pressly/chi/middleware.(*throttler).ServeHTTP(0xc420425800, 0x1c5e080, 0xc4204cd1e0, 0xc4200da4b0)
	/go/src/smasher/vendor/github.com/pressly/chi/middleware/throttler.go:94 +0x3e0
smasher/vendor/github.com/pressly/chi/middleware.RealIP.func1(0x1c5e080, 0xc4204cd1e0, 0xc4200da4b0)
	/go/src/smasher/vendor/github.com/pressly/chi/middleware/realip.go:34 +0xa1
net/http.HandlerFunc.ServeHTTP(0xc420559920, 0x1c5e080, 0xc4204cd1e0, 0xc4200da4b0)
	/usr/local/go/src/net/http/server.go:1726 +0x44
smasher/vendor/github.com/pressly/chi/middleware.RequestID.func1(0x1c5e080, 0xc4204cd1e0, 0xc4200da3c0)
	/go/src/smasher/vendor/github.com/pressly/chi/middleware/request_id.go:68 +0x28e
net/http.HandlerFunc.ServeHTTP(0xc420559940, 0x1c5e080, 0xc4204cd1e0, 0xc4200da3c0)
	/usr/local/go/src/net/http/server.go:1726 +0x44
smasher/vendor/github.com/pressly/chi.(*Mux).ServeHTTP(0xc4202f10e0, 0x1c5e080, 0xc4204cd1e0, 0xc4200da3c0)
	/go/src/smasher/vendor/github.com/pressly/chi/mux.go:79 +0x1f2
net/http.serverHandler.ServeHTTP(0xc420374b00, 0x1c5e080, 0xc4204cd1e0, 0xc4200da0f0)
	/usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc4204a4100, 0x1c64f00, 0xc4204a20c0)
	/usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2293 +0x44d
```

here are the options I am using (the only thing is new is throttling) could it be throttling makes it error 500 ?

here is my code 

```
	r := chi.NewRouter()
	// A good base middleware stack
	r.Use(middleware.RequestID)
	r.Use(middleware.RealIP)
	// Only 5 request will be processed at a time.
	r.Use(middleware.Throttle(5))
	r.Use(middleware.Logger)
	r.Use(middleware.Recoverer)
	// When a client closes their connection midway through a request, the
	// http.CloseNotifier will cancel the request context (ctx).
	r.Use(middleware.CloseNotify)

	// Set a timeout value on the request context (ctx), that will signal
	// through ctx.Done() that the request has timed out and further
	// processing should be stopped.
	r.Use(middleware.Timeout(500 * time.Second))
```

**Comment by pkieltyka** [comment]
@medyagh can you use the master version? middleware.CloseNotify has been removed.

**Comment by pkieltyka** [comment]
i've confirmed that with the stack you listed (minus the CloseNotify middleware), everything works as normal

**Comment by medyagh** [comment]
@pkieltyka I just glide updated with the SHA of the last commit
here is my glide block
```
- package: github.com/pressly/chi
  version: c85a5463d6472673cd8ed5d447b6d5e46413f140
  vcs: git
  subpackages:
  - middleware
  - render
```
and here is my glide.lock block
```
- name: github.com/pressly/chi
  version: c85a5463d6472673cd8ed5d447b6d5e46413f140
  vcs: git
  subpackages:
  - middleware
  - render

```


and I got the same error:
```
panic: runtime error: invalid memory address or nil pointer dereference
2017/02/14 03:29:28 goroutine 90 [running]:
runtime/debug.Stack(0xc4204de2d0, 0x1c59460, 0xc42050cd60)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
smasher/vendor/github.com/pressly/chi/middleware.Recoverer.func1.1(0xc4204de2d0, 0x7fc29d63b8c8, 0xc4204a4280)
	/go/src/smasher/vendor/github.com/pressly/chi/middleware/recoverer.go:23 +0x82
panic(0x1338f20, 0xc42000a040)
	/usr/local/go/src/runtime/panic.go:458 +0x243
main.start_http_server.func4(0x7fc29d63b8c8, 0xc4204a4280, 0xc4204de4b0)
	/go/src/smasher/main.go:150 +0x283

```

**Comment by pkieltyka** [comment]
try it without glide, `go get -u github.com/pressly/chi` and use $GOPATH. if you get the same error, please include gist to your program. Sorry but you'll have to debug your own issues and if you want to report a bug, submit a test case

**Comment by medyagh** [comment]
I will try without glide and go get, but for what it worth, I like to add, I also removed the throttle thing to make sure it wasn't because of that. and also another thing, the thing fails only on the request that takes longer than 30 seconds. (it won't error on other requests)

**Comment by pkieltyka** [comment]
please submit a gist of a broken program and clear instructions on how to reproduce it. If i can reproduce it, I'll definitely fix it

**Comment by medyagh** [comment]
sure here is a gist of the code https://gist.github.com/medyagh/fd03a85e8eb2443a8dbbb42ed4bb05c6

**Comment by pkieltyka** [comment]
@medyagh this is an incomplete program and I dont have memcache either. Please provide a minimal example with no dependencies.

**Comment by medyagh** [comment]
@pkieltyka update, I found out the source of the problem, in kuberentes the default timeout is 2, and there is no way to change it in google kuberentes. so any request taking mroe than 1.30 seconds will throw that error. it will be fine in other places.

however I think it would be nice that the library would throw a better error. (to test it out ,deploy it to google kuberentens and make a reuqest that takes more than 2 minutes to come back)
